version: "3.6"
services:
  db:
    image: advizex/adam-db:latest
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - adamdrive:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Dolce9Lyfe
  app:
    image: advizex/adam-app:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    environment:
      SERVICE_NAME: "app"
  proxy:
    image: advizex/adam-proxy:latest
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - frontend
  tools:
    image: advizex/adam-tools:latest
    depends_on:
      - db
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  adamdrive:
