version: "3.6"
services:
  db:
    image: advizex/adam-db:latest
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - type: volume
        source: adamdrive
        target: /data
        volume:
          nocopy: true
    environment:
      ACCEPT_EULA: "Y"
  app:
    image: advizex/adam-app:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
  proxy:
    image: advizex/adam-proxy:latest
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - frontend
networks:
  frontend:
  backend:
volumes:
  adamdrive:
